alloy:
  enabled: false

minio:
  enabled: false

serviceMonitor:
  enabled: true
  namespaceSelector:
    matchNames:
    - profiles-system
  relabelings:
  - action: replace
    replacement: profiles-system/pyroscope
    sourceLabels:
    - job
    targetLabel: job

pyroscope:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 999m
      memory: 1Gi
  extraArgs:
    log.level: warn
    config.expand-env: true
  extraEnvFrom:
  - secretRef:
      name: pyroscope-env
  podAnnotations:
    # Scrapes itself see https://grafana.com/docs/phlare/latest/operators-guide/deploy-kubernetes/#optional-scrape-your-own-workloads-profiles
    profiles.grafana.com/memory.scrape: "true"
    pyroscope.io/service_name: pyroscope
    profiles.grafana.com/memory.port_name: http2
    profiles.grafana.com/cpu.scrape: "true"
    profiles.grafana.com/cpu.port_name: http2
    profiles.grafana.com/goroutine.scrape: "true"
    profiles.grafana.com/goroutine.port_name: http2
    # profiles.grafana.com/block.scrape: "true"
    # profiles.grafana.com/mutex.scrape: "true"
