
services:
  # Memcached is an in-memory key-value store for small chunks of arbitrary data (strings, objects) from 
  # results of database calls, API calls, or page rendering
  #
  # https://github.com/memcached/memcached
  memcached:
    labels:
      metrics.grafana.com/scrape: false
    image: ${MEMCACHED_IMAGE:-docker.io/memcached:1.6.29-alpine}

  # Use Alloy prometheus.exporter.memcached component instead of memcached-exporter
  # https://github.com/qclaogui/codelab-monitoring/pull/98
  # memcached-exporter:
  #   labels:
  #     - logs.grafana.com/scrape=false
  #     - metrics.grafana.com/scrape=false
  #     # - metrics.grafana.com/job=memcached
  #     - metrics.grafana.com/port=9150
  #     - metrics.grafana.com/interval=15s
  #   image: ${MEMCACHED_EXPORTER_IMAGE:-prom/memcached-exporter:v0.14.3}
  #   command:
  #     - --memcached.address=memcached:11211
  #     - --web.listen-address=0.0.0.0:9150
