
services:
  minio:
    # https://github.com/qclaogui/codelab-monitoring/blob/main/alloy-modules/compose/README.md
    labels:
      logs.grafana.com/scrape: false
      metrics.grafana.com/scrape: true
      metrics.grafana.com/job: minio-job
      metrics.grafana.com/path: /minio/v2/metrics/cluster
      metrics.grafana.com/port: 9000
      metrics.grafana.com/interval: 15s
      metrics.grafana.com/timeout: 10s
    image: ${MINIO_IMAGE:-docker.io/minio/minio:RELEASE.2024-06-22T05-26-45Z}
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/mimir-blocks /data/mimir-ruler /data/mimir-alertmanager && \
        mkdir -p /data/loki-data /data/loki-ruler && \
        mkdir -p /data/tempo-data  && \
        mkdir -p /data/pyroscope-data && \
        minio server /data --console-address ':9001'
    environment:
      - MINIO_ROOT_USER=lgtmp
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
      # # https://github.com/minio/console/issues/3237#issuecomment-1947485286
      # - MINIO_PROMETHEUS_URL="http://gateway:8080/prometheus"
      # - MINIO_PROMETHEUS_JOB_ID="minio-job"
    volumes:
      - minio_data:/data:delegated
    healthcheck:
      test: ["CMD-SHELL", "mc ready local"]
      interval: 2s
      timeout: 1s
      retries: 15
    ports:
      - "9001:9001"

volumes:
  minio_data:
