services:
  pyroscope:
    labels:
      metrics.grafana.com/scrape: false
      profiles.grafana.com/cpu.scrape: true
      profiles.grafana.com/memory.scrape: true
      profiles.grafana.com/goroutine.scrape: true
    depends_on: { minio: { condition: service_healthy } }
    build:
      context: .
      dockerfile: pyroscope.dockerfile
    image: ${PYROSCOPE_IMAGE:-docker.io/grafana/pyroscope:1.7.1}
    configs:
      - source: pyroscope_config_file
        target: /etc/pyroscope/config.yaml
    volumes:
      - ../config/pyroscope:/etc/pyroscope/configs
      - pyroscope_data:/data
    command:
      - -config.file=/etc/pyroscope/config.yaml
      - -target=all
      - -config.expand-env=true
      # - -runtime-config.file=/etc/pyroscope/configs/overrides.yaml
    healthcheck:
      ## execute the `test` in a shell use the form `["CMD-SHELL", "command"]`
      # test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:4040/ready || exit 1" ]
      ## execute the `test` without a shell, use the form: `["CMD", "command", "arg1", "arg2"]`
      test: [ "CMD", "/usr/bin/wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4040/ready" ]
      interval: 2s
      timeout: 1s
      retries: 15
    # expose 34040 port so we can directly access pyroscope inside container
    ports:
      - "34040:4040"

volumes:
  pyroscope_data:
