services:
  # Grafana Tempo is an open source, easy-to-use, and high-scale distributed tracing backend.
  # Tempo is cost-efficient, requiring only object storage to operate, and is deeply integrated
  # with Grafana, Prometheus, and Loki. Tempo can ingest common open source tracing
  # protocols, including Jaeger, Zipkin, and OpenTelemetry.
  #
  # https://github.com/grafana/tempo
  tempo:
    labels:
      metrics.grafana.com/scrape: false
    depends_on: {minio: {condition: service_healthy}}
    image: ${TEMPO_IMAGE:-docker.io/grafana/tempo:2.7.1}
    configs:
      - source: tempo_config_file
        target: /etc/tempo/config.yaml
    restart: always
    volumes:
      - ../config/tempo:/etc/tempo/configs
    command:
      - -config.file=/etc/tempo/config.yaml
      - -target=all
      - -config.expand-env=true
    healthcheck:
      test: ["CMD", "/usr/bin/wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3200/ready"]
      interval: 3s
      timeout: 1s
      retries: 15
    # expose 33200 port so we can directly access tempo inside container
    ports:
      - "33200:3200"
