# ============================================================================ #
#                  Microservices Mode - Profiles
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../common/alloy
- pyroscope

# optional
- ../../monolithic-mode/metrics/mimir

configMapGenerator:
- name: alloy-config
  namespace: monitoring-system
  behavior: replace
  files:
  - config.alloy=profiles.alloy

# Update Pyroscope Microservices Mode endpoint in gateway
- name: nginx-env
  namespace: gateway
  options:
    disableNameSuffixHash: true
  literals:
  - PYROSCOPE_DISTRIBUTOR_HOST=pyroscope-distributor.profiles-system.svc.cluster.local
  - PYROSCOPE_QUERY_FRONTEND_HOST=pyroscope-query-frontend.profiles-system.svc.cluster.local
