multitenancy_enabled: true
analytics:
  reporting_enabled: false

tracing:
  enabled: true
  profiling_enabled: true

compactor:
  data_dir: /data

# https://github.com/grafana/pyroscope/pull/3055
storage:
  backend: s3
  s3:
    bucket_name: pyroscope-data
    endpoint: ${PYROSCOPE_STORAGE_S3_ENDPOINT:-minio:9000}
    access_key_id: ${PYROSCOPE_STORAGE_S3_ACCESS_KEY_ID:-lgtmp}
    secret_access_key: ${PYROSCOPE_STORAGE_S3_SECRET_ACCESS_KEY:-supersecret}
    insecure: ${PYROSCOPE_STORAGE_S3_INSECURE:-true}
    http:
      insecure_skip_verify: true
