---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus.io/service-monitor: "false"
  name: tempo-headless
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: grpc-tempo
    port: 9095
  - name: http-metrics
    port: 3200
  - name: grpc-otlp
    port: 4317
  - name: http-otlp
    port: 4318
