---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  ports:
  - name: grpc-tempo
    port: 9095
  - name: http-metrics
    port: 3200
  - name: grpc-otlp
    port: 4317
    protocol: TCP
  - name: http-otlp
    port: 4318
    protocol: TCP
