apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: tempo
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: tempo-clusterrole
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - configmaps
#   - secrets
#   verbs:
#   - get
#   - watch
#   - list
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: tempo-clusterrolebinding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: tempo-clusterrole
# subjects:
# - kind: ServiceAccount
#   name: tempo
