podAnnotations:
  # https://github.com/grafana/agent-modules/tree/main/modules/kubernetes
  logs.grafana.com/scrape: "true"
  logs.grafana.com/scrub-level: "info"
  pyroscope.io/service_name: tempo
  profiles.grafana.com/cpu.scrape: "true"
  profiles.grafana.com/cpu.port_name: prom-metrics
  profiles.grafana.com/goroutine.scrape: "true"
  profiles.grafana.com/goroutine.port_name: prom-metrics
  profiles.grafana.com/memory.scrape: "true"
  profiles.grafana.com/memory.port_name: prom-metrics

tempo:
  multitenancyEnabled: false
  reportingEnabled: false

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 999m
      memory: 1Gi

  server:
    # -- HTTP server listen port
    http_listen_port: 3100
    grpc_listen_port: 9095

  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://nginx.gateway.svc.cluster.local:8080/api/v1/push"
  
  ingester:
    max_block_duration: 5m

  retention: 1h

  extraArgs:
    config.expand-env: true
  
  extraEnvFrom:
  - secretRef:
      name: tempo-env
