name: Bump common dependency Helm charts
sources:
    alloy:
        name: Get latest "alloy" Helm chart version
        kind: helmchart
        spec:
            name: alloy
            url: https://grafana.github.io/helm-charts
            versionfilter:
                kind: semver
                pattern: '*'
    minio-operator:
        name: Get latest "minio-operator" Helm chart version
        kind: helmchart
        spec:
            name: operator
            url: https://operator.min.io
            versionfilter:
                kind: semver
                pattern: '*'
    minio-tenant:
        name: Get latest "minio-tenant" Helm chart version
        kind: helmchart
        spec:
            name: tenant
            url: https://operator.min.io
            versionfilter:
                kind: semver
                pattern: '*'

conditions:
    alloy:
        name: Ensure Helm chart dependency "alloy" is specified
        kind: yaml
        spec:
            file: kubernetes/common/alloy/kustomization.yaml
            key: $.helmCharts[0].name
            value: alloy
        disablesourceinput: true
    minio-operator:
        name: Ensure Helm chart dependency "minio-operator" is specified
        kind: yaml
        spec:
            file: kubernetes/common/minio-operator/kustomization.yaml
            key: $.helmCharts[0].name
            value: operator
        disablesourceinput: true
    minio-tenant:
        name: Ensure Helm chart dependency "minio-tenant" is specified
        kind: yaml
        spec:
            file: kubernetes/common/minio-tenant/kustomization.yaml
            key: $.helmCharts[0].name
            value: tenant
        disablesourceinput: true

targets:
    minio-operator:
        name: Bump "minio-operator" Helm chart version
        kind: yaml
        spec:
            file: kubernetes/common/minio-operator/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: minio-operator
    minio-tenant:
        name: Bump "minio-tenant" Helm chart version
        kind: yaml
        spec:
            file: kubernetes/common/minio-tenant/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: minio-tenant

    alloy:
        name: Bump "alloy" Helm chart version
        kind: yaml
        spec:
            file: kubernetes/common/alloy/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: alloy
