name: Bump LGTMP stack dependency Helm charts
sources:
    loki:
        name: Get latest "loki" Helm chart version
        kind: helmchart
        spec:
            name: loki
            url: https://grafana.github.io/helm-charts
            versionfilter:
                kind: semver
                pattern: '*'
    grafana:
        name: Get latest "grafana" Helm chart version
        kind: helmchart
        spec:
            name: grafana
            url: https://grafana.github.io/helm-charts
            versionfilter:
                kind: semver
                pattern: '*'
    tempo:
        name: Get latest "tempo" Helm chart version
        kind: helmchart
        spec:
            name: tempo
            url: https://grafana.github.io/helm-charts
            versionfilter:
                kind: semver
                pattern: '*'
    tempo-distributed:
        name: Get latest "tempo-distributed" Helm chart version
        kind: helmchart
        spec:
            name: tempo-distributed
            url: https://grafana.github.io/helm-charts
            versionfilter:
                kind: semver
                pattern: '*'
    mimir-distributed:
        name: Get latest "mimir-distributed" Helm chart version
        kind: helmchart
        spec:
            name: mimir-distributed
            url: https://grafana.github.io/helm-charts
            versionfilter:
                kind: semver
                pattern: '*'
    pyroscope:
        name: Get latest "pyroscope" Helm chart version
        kind: helmchart
        spec:
            name: pyroscope
            url: https://grafana.github.io/helm-charts
            versionfilter:
                kind: semver
                pattern: '*'

conditions:
    loki-in-microservices-mode:
        name: Ensure Helm chart dependency "loki"(microservices-mode) is specified
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/logs/loki/kustomization.yaml
            key: $.helmCharts[0].name
            value: loki
        disablesourceinput: true
    loki-in-read-write-mode:
        name: Ensure Helm chart dependency "loki"(read-write-mode) is specified
        kind: yaml
        spec:
            file: kubernetes/read-write-mode/logs/loki/kustomization.yaml
            key: $.helmCharts[0].name
            value: loki
        disablesourceinput: true
    grafana:
        name: Ensure Helm chart dependency "grafana" is specified
        kind: yaml
        spec:
            file: kubernetes/common/grafana/kustomization.yaml
            key: $.helmCharts[0].name
            value: grafana
        disablesourceinput: true
    tempo-in-microservices-mode:
        name: Ensure Helm chart dependency "tempo-distributed"(microservices-mode) is specified
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/traces/tempo-distributed/kustomization.yaml
            key: $.helmCharts[0].name
            value: tempo-distributed
        disablesourceinput: true
    tempo-in-monolithic-mode:
        name: Ensure Helm chart dependency "tempo"(monolithic-mode) is specified
        kind: yaml
        spec:
            file: kubernetes/monolithic-mode/traces/tempo/kustomization.yaml
            key: $.helmCharts[0].name
            value: tempo
        disablesourceinput: true
    mimir-in-microservices-mode:
        name: Ensure Helm chart dependency "mimir"(microservices-mode) is specified
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/metrics/mimir-distributed/kustomization.yaml
            key: $.helmCharts[0].name
            value: mimir-distributed
        disablesourceinput: true
    pyroscope-in-microservices-mode:
        name: Ensure Helm chart dependency "pyroscope"(microservices-mode) is specified
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/profiles/pyroscope/kustomization.yaml
            key: $.helmCharts[0].name
            value: pyroscope
        disablesourceinput: true
    pyroscope-in-monolithic-mode:
        name: Ensure Helm chart dependency "pyroscope"(monolithic-mode) is specified
        kind: yaml
        spec:
            file: kubernetes/monolithic-mode/profiles/pyroscope/kustomization.yaml
            key: $.helmCharts[0].name
            value: pyroscope
        disablesourceinput: true

targets:
    loki-in-microservices-mode:
        name: Bump "loki"(microservices-mode) Helm chart version
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/logs/loki/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: loki
    loki-in-read-write-mode:
        name: Bump "loki"(read-write-mode) Helm chart version
        kind: yaml
        spec:
            file: kubernetes/read-write-mode/logs/loki/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: loki
    grafana:
        name: Bump "grafana" Helm chart version
        kind: yaml
        spec:
            file: kubernetes/common/grafana/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: grafana
    tempo-in-microservices-mode:
        name: Bump "tempo-distributed"(microservices-mode) Helm chart version
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/traces/tempo-distributed/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: tempo-distributed
    tempo-in-monolithic-mode:
        name: Bump "tempo"(monolithic-mode) Helm chart version
        kind: yaml
        spec:
            file: kubernetes/monolithic-mode/traces/tempo/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: tempo
    mimir-in-microservices-mode:
        name: Bump "mimir-distributed"(microservices-mode) Helm chart version
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/metrics/mimir-distributed/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: mimir-distributed
    pyroscope-in-microservices-mode:
        name: Bump "pyroscope"(microservices-mode) Helm chart version
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/profiles/pyroscope/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: pyroscope
    pyroscope-in-monolithic-mode:
        name: Bump "pyroscope"(monolithic-mode) Helm chart version
        kind: yaml
        spec:
            file: kubernetes/monolithic-mode/profiles/pyroscope/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: pyroscope
