name: Bump LGTMP stack dependency Helm charts
sources:
    loki:
        name: Get latest Helm chart version
        kind: helmchart
        spec:
            name: loki
            url: https://grafana.github.io/helm-charts
            versionfilter:
                kind: semver
                pattern: '*'
    grafana:
        name: Get latest Helm chart version
        kind: helmchart
        spec:
            name: grafana
            url: https://grafana.github.io/helm-charts
            versionfilter:
                kind: semver
                pattern: '*'
    tempo:
        name: Get latest Helm chart version
        kind: helmchart
        spec:
            name: tempo
            url: https://grafana.github.io/helm-charts
            versionfilter:
                kind: semver
                pattern: '*'
    tempo-distributed:
        name: Get latest Helm chart version
        kind: helmchart
        spec:
            name: tempo-distributed
            url: https://grafana.github.io/helm-charts
            versionfilter:
                kind: semver
                pattern: '*'
    mimir-distributed:
        name: Get latest Helm chart version
        kind: helmchart
        spec:
            name: mimir-distributed
            url: https://grafana.github.io/helm-charts
            versionfilter:
                kind: semver
                pattern: '*'
    pyroscope:
        name: Get latest Helm chart version
        kind: helmchart
        spec:
            name: pyroscope
            url: https://grafana.github.io/helm-charts
            versionfilter:
                kind: semver
                pattern: '*'

conditions:
    loki-in-microservices-mode:
        name: Ensure Helm chart "loki" is specified
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/logs/loki/kustomization.yaml
            key: $.helmCharts[0].name
            value: loki
        disablesourceinput: true
    loki-in-read-write-mode:
        name: Ensure Helm chart "loki" is specified
        kind: yaml
        spec:
            file: kubernetes/read-write-mode/logs/loki/kustomization.yaml
            key: $.helmCharts[0].name
            value: loki
        disablesourceinput: true
    grafana:
        name: Ensure Helm chart "grafana" is specified
        kind: yaml
        spec:
            file: kubernetes/common/grafana/kustomization.yaml
            key: $.helmCharts[0].name
            value: grafana
        disablesourceinput: true
    tempo-in-microservices-mode:
        name: Ensure Helm chart "tempo-distributed" is specified
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/traces/tempo-distributed/kustomization.yaml
            key: $.helmCharts[0].name
            value: tempo-distributed
        disablesourceinput: true
    tempo-in-monolithic-mode:
        name: Ensure Helm chart "tempo" is specified
        kind: yaml
        spec:
            file: kubernetes/monolithic-mode/traces/tempo/kustomization.yaml
            key: $.helmCharts[0].name
            value: tempo
        disablesourceinput: true
    mimir-in-microservices-mode:
        name: Ensure Helm chart "mimir-distributed" is specified
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/metrics/mimir-distributed/kustomization.yaml
            key: $.helmCharts[0].name
            value: mimir-distributed
        disablesourceinput: true
    pyroscope-in-microservices-mode:
        name: Ensure Helm chart "pyroscope" is specified
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/profiles/pyroscope/kustomization.yaml
            key: $.helmCharts[0].name
            value: pyroscope
        disablesourceinput: true
    pyroscope-in-monolithic-mode:
        name: Ensure Helm chart "pyroscope" is specified
        kind: yaml
        spec:
            file: kubernetes/monolithic-mode/profiles/pyroscope/kustomization.yaml
            key: $.helmCharts[0].name
            value: pyroscope
        disablesourceinput: true

targets:
    loki-in-microservices-mode:
        name: Bump "loki" Helm chart version to {{ source "loki" }}
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/logs/loki/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: loki
    loki-in-read-write-mode:
        name: Bump "loki" Helm chart version to {{ source "loki" }}
        kind: yaml
        spec:
            file: kubernetes/read-write-mode/logs/loki/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: loki
    grafana:
        name: Bump "grafana" Helm chart version to {{ source "grafana" }}
        kind: yaml
        spec:
            file: kubernetes/common/grafana/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: grafana
    tempo-in-microservices-mode:
        name: Bump "tempo-distributed" Helm chart version to {{ source "tempo-distributed" }}
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/traces/tempo-distributed/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: tempo-distributed
    tempo-in-monolithic-mode:
        name: Bump "tempo" Helm chart version to {{ source "tempo" }}
        kind: yaml
        spec:
            file: kubernetes/monolithic-mode/traces/tempo/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: tempo
    mimir-in-microservices-mode:
        name: Bump "mimir-distributed" Helm chart version to {{ source "mimir-distributed" }}
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/metrics/mimir-distributed/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: mimir-distributed
    pyroscope-in-microservices-mode:
        name: Bump "pyroscope" Helm chart version to {{ source "pyroscope" }}
        kind: yaml
        spec:
            file: kubernetes/microservices-mode/profiles/pyroscope/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: pyroscope
    pyroscope-in-monolithic-mode:
        name: Bump "pyroscope" Helm chart version to {{ source "pyroscope" }}
        kind: yaml
        spec:
            file: kubernetes/monolithic-mode/profiles/pyroscope/kustomization.yaml
            key: $.helmCharts[0].version
        sourceid: pyroscope
