name: Update Docker Compose image versions

sources:
  grafana-version:
    kind: dockerimage
    spec:
      image: docker.io/grafana/grafana
      versionfilter:
        kind: semver
        pattern: "~11.x"

  alloy-version:
    kind: dockerimage
    spec:
      image: docker.io/grafana/alloy
      versionfilter:
        kind: semver
        pattern: "~1.x"

  loki-version:
    kind: dockerimage
    spec:
      image: docker.io/grafana/loki
      versionfilter:
        kind: semver
        pattern: "~3.x"

conditions:
  check-grafana-image:
    kind: dockerimage
    disablesourceinput: true
    spec:
      image: docker.io/grafana/grafana
      tag: '{{ source "grafana-version" }}'

  check-alloy-image:
    kind: dockerimage
    disablesourceinput: true
    spec:
      image: docker.io/grafana/alloy
      tag: '{{ source "alloy-version" }}'

  check-loki-image:
    kind: dockerimage
    disablesourceinput: true
    spec:
      image: docker.io/grafana/loki
      tag: '{{ source "loki-version" }}'

targets:
  update-grafana-image-version-in-compose-include:
    kind: yaml
    sourceid: grafana-version
    transformers:
      - addprefix: "${GRAFANA_IMAGE:-docker.io/grafana/grafana:"
      - addsuffix: "}"
    spec:
      file: docker-compose/common/compose-include/grafana.yaml
      key: $.services.grafana.image

  update-grafana-image-version-in-env:
    kind: "file"
    sourceid: grafana-version
    spec:
      files:
        - docker-compose/common/config/.env
      matchpattern: 'GRAFANA_IMAGE=grafana/grafana:.*'
      replacepattern: 'GRAFANA_IMAGE=grafana/grafana:{{ source "grafana-version" }}'

  update-alloy-image-version-in-compose-include:
    kind: yaml
    sourceid: alloy-version
    transformers:
      - addprefix: "${ALLOY_IMAGE:-docker.io/grafana/alloy:"
      - addsuffix: "}"
    spec:
      file: docker-compose/common/compose-include/alloy.yaml
      key: $.services.alloy.image

  update-alloy-image-version-in-env:
    kind: "file"
    sourceid: alloy-version
    spec:
      files:
        - docker-compose/common/config/.env
      matchpattern: 'ALLOY_IMAGE=grafana/alloy:.*'
      replacepattern: 'ALLOY_IMAGE=grafana/alloy:{{ source "alloy-version" }}'

  update-loki-image-version-in-compose-include:
    kind: yaml
    sourceid: loki-version
    transformers:
      - addprefix: "${LOKI_IMAGE:-docker.io/grafana/loki:"
      - addsuffix: "}"
    spec:
      file: docker-compose/common/compose-include/loki.yaml
      key: $.services.loki.image

  update-loki-image-version-in-all-in-one-mode-logs:
    kind: yaml
    sourceid: loki-version
    transformers:
      - addprefix: "${LOKI_IMAGE:-docker.io/grafana/loki:"
      - addsuffix: "}"
    spec:
      file: docker-compose/monolithic-mode/all-in-one/compose.yaml
      key: $.services.loki.image

  update-loki-image-version-in-read-write-mode-logs:
    kind: yaml
    sourceid: loki-version
    transformers:
      - addprefix: "&lokiImage ${LOKI_IMAGE:-docker.io/grafana/loki:"
      - addsuffix: "}"
    spec:
      file: docker-compose/read-write-mode/logs/compose.yaml
      key: $.services.loki-read.image

  update-loki-image-version-in-microservices-mode-logs:
    kind: yaml
    sourceid: loki-version
    transformers:
      - addprefix: "&lokiImage ${LOKI_IMAGE:-docker.io/grafana/loki:"
      - addsuffix: "}"
    spec:
      file: docker-compose/microservices-mode/logs/compose.yaml
      key: $.services.distributor.image

  update-loki-image-version-in-env:
    kind: "file"
    sourceid: loki-version
    spec:
      files:
        - docker-compose/common/config/.env
      matchpattern: 'LOKI_IMAGE=grafana/loki:.*'
      replacepattern: 'LOKI_IMAGE=grafana/loki:{{ source "loki-version" }}'
