apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://github.com/bitnami/charts/tree/main/bitnami/memcached
helmCharts:
- name: memcached
  repo: oci://registry-1.docker.io/bitnamicharts
  version: 7.0.0
  releaseName: memcached
  namespace: memcached-system
  includeCRDs: false
  skipTests: true
  valuesFile: values-k3d-k3s.yaml

resources:
- namespace.yaml
- ../../../monitoring-mixins/memcached-mixin/deploy

# # only if auth.enabled=true
# secretGenerator:
# - name: memcached-credentials
#   namespace: memcached-system
#   literals:
#   - "memcached-password=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm"
