
auth:
  enabled: false
  username: lgtmp
  existingSecret: memcached-credentials

# args:
# - -m 256Mi
# - --extended=modern,track_sizes
# - -I 5m
# - -c 16384
# - -v
# - -u 11211

resources:
  limits:
    memory: 320Mi
    cpu: 999m
  requests:
    memory: 64Mi
    cpu: 50m

podAnnotations:
  logs.grafana.com/scrape: "true"
