apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tracing-system
helmCharts:
- name: tempo-distributed
  version: 1.10.0
  repo: https://grafana.github.io/helm-charts
  releaseName: tempo-distributed
  namespace: tracing-system
  includeCRDs: false
  skipTests: true
  additionalValuesFiles:
  - values-k3d-k3s.yaml
images:
- name: docker.io/grafana/tempo
  newTag: 2.4.1
resources:
- namespace.yaml
