apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tracing-system
helmCharts:
- name: tempo-distributed
  version: 1.41.1
  repo: https://grafana.github.io/helm-charts
  releaseName: tempo-distributed
  namespace: tracing-system
  includeCRDs: false
  skipTests: true
  additionalValuesFiles:
  - values-k3d-k3s.yaml
resources:
- namespace.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: tempo-distributed-distributor-discovery
      namespace: tracing-system
    spec:
      publishNotReadyAddresses: true
