useExternalConfig: false
externalConfigSecretName: tempo-distributed-config
externalRuntimeConfigName: tempo-distributed-runtime
externalConfigVersion: '0'

reportingEnabled: false
multitenancyEnabled: false

ingester:
  podAnnotations:
    logs.grafana.com/scrape: "true"
    profiles.grafana.com/cpu.scrape: "true"
    profiles.grafana.com/cpu.port_name: http-metrics
    profiles.grafana.com/goroutine.scrape: "true"
    profiles.grafana.com/goroutine.port_name: http-metrics
    profiles.grafana.com/memory.scrape: "true"
    profiles.grafana.com/memory.port_name: http-metrics
  extraArgs:
  - -config.expand-env=true
  extraEnvFrom:
  - secretRef:
      name: tempo-distributed-env

metricsGenerator:
  podAnnotations:
    logs.grafana.com/scrape: "true"
    profiles.grafana.com/cpu.scrape: "true"
    profiles.grafana.com/cpu.port_name: http-metrics
    profiles.grafana.com/goroutine.scrape: "true"
    profiles.grafana.com/goroutine.port_name: http-metrics
    profiles.grafana.com/memory.scrape: "true"
    profiles.grafana.com/memory.port_name: http-metrics
  enabled: true
  extraArgs: []
  extraEnvFrom: []
  config:
    processor:
      span_metrics:
        # Configure extra dimensions to add as metric labels.
        dimensions:
        - http.method
        - http.target
        - http.status_code
        - service.version
      # Service graph metrics create node and edge metrics for determinng service interactions.
      service_graphs:
        # Configure extra dimensions to add as metric labels.
        dimensions:
        - http.method
        - http.target
        - http.status_code
        - service.version
    storage:
      path: /var/tempo/wal
      remote_write_add_org_id_header: true
      remote_write:
      - url: http://nginx.gateway.svc.cluster.local:8080/api/v1/push
        send_exemplars: true
        send_native_histograms: true
        headers:
          X-Scope-OrgID: "anonymous"
    # traces_storage:
    #   path: /var/tempo/traces

distributor:
  podAnnotations:
    logs.grafana.com/scrape: "true"
    profiles.grafana.com/cpu.scrape: "true"
    profiles.grafana.com/cpu.port_name: http-metrics
    profiles.grafana.com/goroutine.scrape: "true"
    profiles.grafana.com/goroutine.port_name: http-metrics
    profiles.grafana.com/memory.scrape: "true"
    profiles.grafana.com/memory.port_name: http-metrics
  extraArgs:
  - -config.expand-env=true
  extraEnvFrom:
  - secretRef:
      name: tempo-distributed-env

compactor:
  podAnnotations:
    logs.grafana.com/scrape: "true"
    profiles.grafana.com/cpu.scrape: "true"
    profiles.grafana.com/cpu.port_name: http-metrics
    profiles.grafana.com/goroutine.scrape: "true"
    profiles.grafana.com/goroutine.port_name: http-metrics
    profiles.grafana.com/memory.scrape: "true"
    profiles.grafana.com/memory.port_name: http-metrics
  extraArgs:
  - -config.expand-env=true
  extraEnvFrom:
  - secretRef:
      name: tempo-distributed-env

querier:
  podAnnotations:
    logs.grafana.com/scrape: "true"
    profiles.grafana.com/cpu.scrape: "true"
    profiles.grafana.com/cpu.port_name: http-metrics
    profiles.grafana.com/goroutine.scrape: "true"
    profiles.grafana.com/goroutine.port_name: http-metrics
    profiles.grafana.com/memory.scrape: "true"
    profiles.grafana.com/memory.port_name: http-metrics
  extraArgs:
  - -config.expand-env=true
  extraEnvFrom:
  - secretRef:
      name: tempo-distributed-env

queryFrontend:
  podAnnotations:
    logs.grafana.com/scrape: "true"
    profiles.grafana.com/cpu.scrape: "true"
    profiles.grafana.com/cpu.port_name: http-metrics
    profiles.grafana.com/goroutine.scrape: "true"
    profiles.grafana.com/goroutine.port_name: http-metrics
    profiles.grafana.com/memory.scrape: "true"
    profiles.grafana.com/memory.port_name: http-metrics
  extraArgs:
  - -config.expand-env=true
  extraEnvFrom:
  - secretRef:
      name: tempo-distributed-env

traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true

server:
  httpListenPort: 3100
  logLevel: info
  logFormat: logfmt
  grpc_server_max_recv_msg_size: 4194304
  grpc_server_max_send_msg_size: 4194304

storage:
  trace:
    backend: s3

# Global overrides
global_overrides:
  per_tenant_override_config: /runtime-config/overrides.yaml

# Per tenants overrides
overrides: |
  overrides: {}

memcached:
  enabled: false

metaMonitoring:
  serviceMonitor:
    enabled: false
    namespace: null

minio:
  enabled: false

gateway:
  enabled: false
