log_level: DEBUG
trace_printer: text

ebpf:
  enable_context_propagation: true

routes:
  ignored_patterns:
    - /health
    - /ready
    - /live
    - /metrics
  patterns:
    - /api/v1/push
    - /prometheus
    - /prometheus/api/v1/series
    - /prometheus/api/v1/query_range
    - /prometheus/api/v1/query_exemplars
    - /loki/api/v1/push
    - /loki/api/v1/query_range
    - /loki/api/v1/labels
    - /otlp/v1/traces
    - /otlp/v1/metrics
    - /api/traces/{trace_id}
  unmatched: path

otel_metrics_export:
  features:
    - application
    - application_span
    - application_service_graph
    - application_process
    - network

network:
  enable: true

attributes:
  select:
    "*":
      include: ["*"]

internal_metrics:
  prometheus:
    port: 6060
    path: /internal/metrics
