version: "2"

linters:
  enable:
    - copyloopvar
    - errorlint
    - goconst
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    errcheck:
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - (github.com/go-kit/log.Logger).Log
    errorlint:
      errorf: false
      asserts: false
    goconst:
      min-len: 5
      min-occurrences: 5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: if-return
      - linters:
          - goconst
        path: '(.+)_test\.go'
    paths:
      - .*.pb.go
      - third_party$
      - builtin$
      - examples$
      - kubernetes/
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*.pb.go
      - third_party$
      - builtin$
      - examples$