run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m

linters:
  enable:
    - errorlint
    - goconst
    - gofmt
    - goimports
    - revive
    - ineffassign
    - staticcheck
    - misspell
    - unconvert
    - unparam
    - govet
    - typecheck
    - copyloopvar

linters-settings:
  errcheck:
    # List of functions to exclude from checking, where each entry is a single function to exclude.
    # See https://github.com/kisielk/errcheck#excluding-functions for details.
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)
      - (github.com/go-kit/log.Logger).Log

  errorlint:
    # Do not check for plain type assertions and type switches.
    asserts: false
    # Check whether fmt.Errorf uses the %w verb for formatting errors.
    # See the https://github.com/polyfloyd/go-errorlint for caveats.
    # Default: true
    errorf: false
  
  goconst:
    min-len: 5
    min-occurrences: 5
    ignore-tests: true

issues:
  exclude-files:
    - .*.pb.go
  exclude-rules:
    - linters: [revive]
      text: "if-return"
