# ============================================================================ #
#                  Monolithic Mode - All in one
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../common/alloy
- ../logs/loki
- ../traces/tempo
- ../metrics/mimir
- ../profiles/pyroscope
- ../../common/kube-state-metrics
- ../../common/prometheus-node-exporter
# - ../../common/grafana-pdc-agent
# - ../../common/opencost

# secretGenerator:
# - name: grafana-pdc-agent-env
#   namespace: monitoring-system
#   literals:
#   - TOKEN=xxx
#   - HOSTED_GRAFANA_ID=xxx
#   - CLUSTER=prod-us-central-0

configMapGenerator:
- name: alloy-config
  namespace: monitoring-system
  behavior: replace
  files:
  - config.alloy=all-in-one.alloy

# Update LGTMP endpoint in gateway
- name: nginx-templates
  namespace: gateway
  options:
    disableNameSuffixHash: true
  files:
  - gateway_loki.conf.template=configs/gateway_loki.conf
  - gateway_mimir.conf.template=configs/gateway_mimir.conf
  - gateway_pyroscope.conf.template=configs/gateway_pyroscope.conf
  - gateway_tempo.conf.template=configs/gateway_tempo.conf
