module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.22.4

toolchain go1.23.0

require github.com/monitoring-mixins/mixtool v0.0.0-20250707094217-1abe34c3187d // cmd/mixtool
