module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.22.4

toolchain go1.23.0

require github.com/monitoring-mixins/mixtool v0.0.0-20240806195600-448a81c91e51 // cmd/mixtool
