module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.25.1

replace github.com/drone/go-scm => github.com/olblak/go-scm v1.26.1-0.20240829085250-adc387402cba

require github.com/updatecli/updatecli v0.107.0
