apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://github.com/bitnami/charts/tree/main/bitnami/redis/
helmCharts:
- name: redis
  repo: oci://registry-1.docker.io/bitnamicharts
  version: 20.0.1
  releaseName: redis
  namespace: redis-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml

resources:
- namespace.yaml

# redis credentials
secretGenerator:
- name: redis-credentials
  namespace: redis-system
  literals:
  - "redis-password=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm"
