
## @param architecture Redis&reg; architecture. Allowed values: `standalone` or `replication`
##
architecture: standalone

auth:
  enabled: true
  existingSecret: redis-credentials

commonConfiguration: |-
  appendonly yes
  maxmemory 64mb
  maxmemory-policy allkeys-lru
  save ""

master:
  podAnnotations:
    logs.grafana.com/scrape: "true"
