name: Update grafana image versions

sources:
  grafana-version:
    kind: dockerimage
    spec:
      image: docker.io/grafana/grafana
      versionfilter:
        kind: semver
        pattern: "~11.x"

conditions:
  check-grafana-image:
    kind: dockerimage
    disablesourceinput: true
    spec:
      image: docker.io/grafana/grafana
      tag: '{{ source "grafana-version" }}'

targets:
  update-grafana-image-version-in-env:
    kind: "file"
    sourceid: grafana-version
    spec:
      files:
        - docker-compose/common/config/.env
      matchpattern: 'GRAFANA_IMAGE=grafana/grafana:.*'
      replacepattern: 'GRAFANA_IMAGE=grafana/grafana:{{ source "grafana-version" }}'

  update-grafana-image-version-in-compose-include:
    kind: yaml
    sourceid: grafana-version
    transformers:
      - addprefix: "${GRAFANA_IMAGE:-docker.io/grafana/grafana:"
      - addsuffix: "}"
    spec:
      file: docker-compose/common/compose-include/grafana.yaml
      key: $.services.grafana.image

  update-grafana-image-version-in-compose-override:
    kind: yaml
    sourceid: grafana-version
    transformers:
      - addprefix: "${GRAFANA_IMAGE:-docker.io/grafana/grafana:"
      - addsuffix: "}"
    spec:
      file: compose.override.yaml
      key: $.services.grafana.image
