name: Update loki image versions

sources:
  loki-version:
    kind: dockerimage
    spec:
      image: docker.io/grafana/loki
      versionfilter:
        kind: semver
        pattern: "~3.x"

conditions:
  check-loki-image:
    kind: dockerimage
    disablesourceinput: true
    spec:
      image: docker.io/grafana/loki
      tag: '{{ source "loki-version" }}'

targets:
  update-loki-image-version-in-env:
    kind: "file"
    sourceid: loki-version
    spec:
      files:
        - docker-compose/common/config/.env
      matchpattern: 'LOKI_IMAGE=grafana/loki:.*'
      replacepattern: 'LOKI_IMAGE=grafana/loki:{{ source "loki-version" }}'

  update-loki-image-version-in-compose-include:
    kind: yaml
    sourceid: loki-version
    transformers:
      - addprefix: "${LOKI_IMAGE:-docker.io/grafana/loki:"
      - addsuffix: "}"
    spec:
      file: docker-compose/common/compose-include/loki.yaml
      key: $.services.loki.image

  update-loki-image-version-in-all-in-one-mode:
    kind: yaml
    sourceid: loki-version
    transformers:
      - addprefix: "${LOKI_IMAGE:-docker.io/grafana/loki:"
      - addsuffix: "}"
    spec:
      file: docker-compose/monolithic-mode/all-in-one/compose.yaml
      key: $.services.loki.image

  update-loki-image-version-in-read-write-mode:
    kind: yaml
    sourceid: loki-version
    transformers:
      - addprefix: "&lokiImage ${LOKI_IMAGE:-docker.io/grafana/loki:"
      - addsuffix: "}"
    spec:
      file: docker-compose/read-write-mode/logs/compose.yaml
      key: $.services.loki-read.image

  update-loki-image-version-in-microservices-mode:
    kind: file
    sourceid: loki-version
    spec:
      file: docker-compose/microservices-mode/logs/compose.yaml
      matchpattern: 'docker.io/grafana/loki:.*'
      replacepattern: 'docker.io/grafana/loki:{{ source "loki-version" }}}'
