# Multi-tenant mode is set in the configuration with auth_enabled: true
# https://grafana.com/docs/loki/latest/operations/multi-tenancy/
auth_enabled: true

analytics:
 reporting_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info
  log_format: json

common:
  compactor_address: http://compactor:3100
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      bucketnames: loki-data
      endpoint: ${LOKI_S3_ENDPOINT:-minio:9000}
      access_key_id: ${LOKI_S3_ACCESS_KEY_ID:-lgtmp}
      secret_access_key: ${LOKI_S3_SECRET_ACCESS_KEY:-supersecret}
      insecure: ${LOKI_S3_INSECURE:-true}
      s3forcepathstyle: true
      http_config:
        insecure_skip_verify: true

index_gateway:
  mode: simple

bloom_build:
  enabled: true
  builder:
    planner_address: bloom-planner:9095

bloom_gateway:
  enabled: true
  client:
    addresses: bloom-gateway:9095
    cache_results: true
    results_cache:
      cache:
        memcached_client:
          addresses: "dns+memcached:11211"

compactor:
  working_directory: /loki/compactor
  compactor_ring:
    kvstore:
      store: memberlist

frontend:
  tail_proxy_url: http://querier:3100
  scheduler_address: query-scheduler:9095
frontend_worker:
  scheduler_address: query-scheduler:9095

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
  wal:
    dir: /loki/wal

pattern_ingester:
  enabled: true

limits_config:
  bloom_gateway_enable_filtering: true
  bloom_compactor_enable_compaction: true
  max_global_streams_per_user: 0
  ingestion_rate_mb: 50000
  ingestion_burst_size_mb: 50000
  volume_enabled: true

memberlist:
  join_members:
  - loki-memberlist:7946

# https://github.com/grafana/loki/blob/main/docs/sources/configure/_index.md#query_range
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      memcached_client:
        addresses: "dns+memcached:11211"

  cache_index_stats_results: true
  index_stats_results_cache:
    cache:
      memcached_client:
        addresses: "dns+memcached:11211"

ruler:
  storage:
    type: s3
    s3:
      bucketnames: loki-ruler

runtime_config:
  file: /etc/loki/configs/runtime.yaml

schema_config:
  configs:
  - from: "2024-04-08"
    index:
      prefix: loki_index_
      period: 24h
    object_store: s3
    store: tsdb
    schema: v13

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    index_gateway_client:
      server_address: dns:///index-gateway:9095
  bloom_shipper:
    working_directory: /loki/bloomshipper

chunk_store_config:
  chunk_cache_config:
    memcached_client:
      addresses: "dns+memcached:11211"
