crds:
  create: false
configReloader:
  enabled: false
alloy:
  resources:
    limits:
      cpu: 250m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi
  configMap:
    create: false
    name: alloy-config
    key: config.alloy
  clustering:
    enabled: true
  stabilityLevel: experimental
  # storagePath: /tmp/alloy
  enableReporting: false
  envFrom:
  - secretRef:
      name: alloy-env
      optional: true
  extraPorts:
  - name: "grpc-otlp"
    port: 4317
    targetPort: 4317
    protocol: "TCP"
  - name: "http-otlp"
    port: 4318
    targetPort: 4318
    protocol: "TCP"
  - name: "zipkin"
    port: 9411
    targetPort: 9411
    protocol: "TCP"
  - name: jaeger-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  mounts:
    # TODO(qc) remove this by Alloy import.git
    extra:
    - name: modules-receiver-provider
      mountPath: /etc/alloy/modules/provider
    - name: modules-kubernetes-metrics
      mountPath: /etc/alloy/modules/kubernetes/metrics
    - name: modules-kubernetes-logs
      mountPath: /etc/alloy/modules/kubernetes/logs
    - name: modules-kubernetes-traces
      mountPath: /etc/alloy/modules/kubernetes/traces
    - name: modules-kubernetes-profiles
      mountPath: /etc/alloy/modules/kubernetes/profiles
    - name: modules-kubernetes-jobs
      mountPath: /etc/alloy/modules/kubernetes/jobs
  securityContext:
    privileged: true

serviceMonitor:
  enabled: true

ingress:
  enabled: true
  faroPort: 12345
  hosts:
  - alloy.localhost

controller:
  type: statefulset
  enableStatefulSetAutoDeletePVC: true
  replicas: 1
  volumes:
    extra:
    - name: modules-receiver-provider
      configMap:
        name: alloy-modules-receiver-provider
    - name: modules-kubernetes-metrics
      configMap:
        name: alloy-modules-kubernetes-metrics
    - name: modules-kubernetes-logs
      configMap:
        name: alloy-modules-kubernetes-logs
    - name: modules-kubernetes-traces
      configMap:
        name: alloy-modules-kubernetes-traces
    - name: modules-kubernetes-profiles
      configMap:
        name: alloy-modules-kubernetes-profiles
    - name: modules-kubernetes-jobs
      configMap:
        name: alloy-modules-kubernetes-jobs
  podAnnotations:
    # https://github.com/qclaogui/codelab-monitoring/blob/main/alloy-modules/compose/README.md
    logs.grafana.com/scrape: "true"
    # logs.grafana.com/tenant: ".*"       # Allow a pod to override the tenant for its logs.
    pyroscope.io/service_name: alloy
    profiles.grafana.com/memory.scrape: "false"
    profiles.grafana.com/memory.port_name: "http-metrics"
    profiles.grafana.com/cpu.scrape: "false"
    profiles.grafana.com/cpu.port_name: "http-metrics"
    profiles.grafana.com/goroutine.scrape: "false"
    profiles.grafana.com/goroutine.port_name: "http-metrics"
  nodeSelector:
    kubernetes.io/os: linux