# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- nginx/nginx-dep.yaml
- nginx/nginx-svc.yaml

replicas:
- count: 2
  name: nginx

images:
- name: nginx
  newName: nginxinc/nginx-unprivileged
  newTag: 1.27-alpine

configMapGenerator:
- name: nginx-conf
  namespace: gateway
  files:
  - nginx.conf.template=nginx/nginx.conf
- name: nginx-entrypoint-scripts
  namespace: gateway
  files:
  - nginx/docker-entrypoint.d/10-default-lgtmp.envsh
  - nginx/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
  - nginx/docker-entrypoint.d/15-local-resolvers.envsh
  - nginx/docker-entrypoint.d/20-envsubst-on-templates.sh
  - nginx/docker-entrypoint.d/30-tune-worker-processes.sh

- name: nginx-templates
  namespace: gateway
  options:
    disableNameSuffixHash: true
  files:
  - gateway_loki.conf.template=nginx/gateway_loki.conf
  - gateway_mimir.conf.template=nginx/gateway_mimir.conf
  - gateway_pyroscope.conf.template=nginx/gateway_pyroscope.conf
