# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

resources:
- prometheus-alerts.yaml
- prometheus-rules.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
  annotations:
    grafana_dashboard_folder: "/dashboards/mimir-mixin"

configMapGenerator:
- name: mimir-alertmanager-resources.json
  files:
  - dashboards_out/mimir-alertmanager-resources.json
- name: mimir-alertmanager.json
  files:
  - dashboards_out/mimir-alertmanager.json
- name: mimir-compactor-resources.json
  files:
  - dashboards_out/mimir-compactor-resources.json
- name: mimir-compactor.json
  files:
  - dashboards_out/mimir-compactor.json
- name: mimir-config.json
  files:
  - dashboards_out/mimir-config.json
- name: mimir-object-store.json
  files:
  - dashboards_out/mimir-object-store.json
- name: mimir-overrides.json
  files:
  - dashboards_out/mimir-overrides.json
- name: mimir-overview-networking.json
  files:
  - dashboards_out/mimir-overview-networking.json
- name: mimir-overview-resources.json
  files:
  - dashboards_out/mimir-overview-resources.json
- name: mimir-overview.json
  files:
  - dashboards_out/mimir-overview.json
- name: mimir-queries.json
  files:
  - dashboards_out/mimir-queries.json
- name: mimir-reads-networking.json
  files:
  - dashboards_out/mimir-reads-networking.json
- name: mimir-reads-resources.json
  files:
  - dashboards_out/mimir-reads-resources.json
- name: mimir-reads.json
  files:
  - dashboards_out/mimir-reads.json
- name: mimir-remote-ruler-reads-networking.json
  files:
  - dashboards_out/mimir-remote-ruler-reads-networking.json
- name: mimir-remote-ruler-reads-resources.json
  files:
  - dashboards_out/mimir-remote-ruler-reads-resources.json
- name: mimir-remote-ruler-reads.json
  files:
  - dashboards_out/mimir-remote-ruler-reads.json
- name: mimir-rollout-progress.json
  files:
  - dashboards_out/mimir-rollout-progress.json
- name: mimir-ruler.json
  files:
  - dashboards_out/mimir-ruler.json
- name: mimir-scaling.json
  files:
  - dashboards_out/mimir-scaling.json
- name: mimir-slow-queries.json
  files:
  - dashboards_out/mimir-slow-queries.json
- name: mimir-tenants.json
  files:
  - dashboards_out/mimir-tenants.json
- name: mimir-top-tenants.json
  files:
  - dashboards_out/mimir-top-tenants.json
- name: mimir-writes-networking.json
  files:
  - dashboards_out/mimir-writes-networking.json
- name: mimir-writes-resources.json
  files:
  - dashboards_out/mimir-writes-resources.json
- name: mimir-writes.json
  files:
  - dashboards_out/mimir-writes.json
