apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: prometheus-operator-crds
  repo: https://prometheus-community.github.io/helm-charts
  version: 17.0.2
  includeCRDs: false
