# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

resources:
- prometheus-alerts.yaml
- prometheus-rules.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
  annotations:
    grafana_dashboard_folder: "/dashboards/kubernetes-mixin"

configMapGenerator:
- name: apiserver.json
  files:
  - dashboards_out/apiserver.json
- name: cluster-total.json
  files:
  - dashboards_out/cluster-total.json
- name: controller-manager.json
  files:
  - dashboards_out/controller-manager.json
- name: k8s-resources-cluster.json
  files:
  - dashboards_out/k8s-resources-cluster.json
- name: k8s-resources-namespace.json
  files:
  - dashboards_out/k8s-resources-namespace.json
- name: k8s-resources-node.json
  files:
  - dashboards_out/k8s-resources-node.json
- name: k8s-resources-pod.json
  files:
  - dashboards_out/k8s-resources-pod.json
- name: k8s-resources-workload.json
  files:
  - dashboards_out/k8s-resources-workload.json
- name: k8s-resources-workloads-namespace.json
  files:
  - dashboards_out/k8s-resources-workloads-namespace.json
- name: kubelet.json
  files:
  - dashboards_out/kubelet.json
- name: namespace-by-pod.json
  files:
  - dashboards_out/namespace-by-pod.json
- name: namespace-by-workload.json
  files:
  - dashboards_out/namespace-by-workload.json
- name: persistentvolumesusage.json
  files:
  - dashboards_out/persistentvolumesusage.json
- name: pod-total.json
  files:
  - dashboards_out/pod-total.json
- name: proxy.json
  files:
  - dashboards_out/proxy.json
- name: scheduler.json
  files:
  - dashboards_out/scheduler.json
- name: workload-total.json
  files:
  - dashboards_out/workload-total.json
