opencost:
  exporter:
    defaultClusterId: k3d-k3s-codelab
  metrics:
    serviceMonitor:
      enabled: true
      relabelings:
      - replacement: integrations/kubernetes/opencost
        sourceLabels:
        - job
        targetLabel: job

  prometheus:
    external:
      enabled: true
      url: http://nginx.gateway.svc.cluster.local.:8080/prometheus
    internal:
      enabled: false

  # ui:
  #   enabled: true
  #   ingress:
  #     enabled: true
  #     hosts:
  #     - opencost.localhost
