apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.18.2
  releaseName: cert-manager
  namespace: cert-manager
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml
resources:
- namespace.yaml
- selfsigned-root-clusterissuer.yaml
