apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: pyroscope
  version: 1.13.4
  repo: https://grafana.github.io/helm-charts
  releaseName: pyroscope
  namespace: profiles-system
  includeCRDs: false
  additionalValuesFiles:
  - values-k3d-k3s.yaml
resources:
- namespace.yaml
secretGenerator:
- name: pyroscope-env
  namespace: profiles-system
  literals:
  - PYROSCOPE_STORAGE_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm
generators:
- |-
  apiVersion: builtin
  kind: ConfigMapGenerator
  metadata:
    name: pyroscope-config
    namespace: profiles-system
  behavior: replace
  files:
  - config.yaml=configs/pyroscope.yaml
