# ============================================================================ #
#                  Microservices Mode - Traces
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../common/alloy
- tempo-distributed

# optional
- ../../monolithic-mode/metrics/mimir
- ../../monolithic-mode/logs/loki

secretGenerator:
- name: tempo-distributed-env
  namespace: tracing-system
  literals:
  - TEMPO_S3_SECRET_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm
  - JAEGER_AGENT_HOST=alloy.monitoring-system.svc.cluster.local
  - JAEGER_AGENT_PORT=6831
  - JAEGER_TAGS=app=tempo
  - JAEGER_SAMPLER_TYPE=const
  - JAEGER_SAMPLER_PARAM=1

configMapGenerator:
- name: alloy-config
  namespace: monitoring-system
  behavior: replace
  files:
  - config.alloy=traces.alloy

- name: tempo-distributed-config
  namespace: tracing-system
  behavior: replace
  files:
  - tempo.yaml=configs/tempo-distributed.yaml
- name: tempo-distributed-runtime
  namespace: tracing-system
  behavior: replace
  files:
  - configs/overrides.yaml

# Update Tempo Microservices Mode endpoint in gateway
- name: nginx-templates
  namespace: gateway
  options:
    disableNameSuffixHash: true
  files:
  - gateway_tempo.conf.template=configs/gateway_tempo.conf
  - gateway_mimir.conf.template=configs/gateway_mimir.conf
  - gateway_loki.conf.template=configs/gateway_loki.conf
- name: nginx-env
  namespace: gateway
  options:
    disableNameSuffixHash: true
  literals:
  - TEMPO_DISTRIBUTOR_HOST=tempo-distributed-distributor.tracing-system.svc.cluster.local
  - TEMPO_INGESTER_HOST=tempo-distributed-ingester.tracing-system.svc.cluster.local
  - TEMPO_QUERY_FRONTEND_HOST=tempo-distributed-query-frontend.tracing-system.svc.cluster.local
  - TEMPO_COMPACTOR_HOST=tempo-distributed-compactor.tracing-system.svc.cluster.local
