services:
  # override included service grafana for dashboards pre-provisioning
  grafana:
    volumes:
      - ./beyla/beyla-red-metrics.json:/var/lib/grafana/dashboards/beyla-red-metrics.json
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/beyla-red-metrics.json
