services:
  # override included service grafana for dashboards pre-provisioning
  grafana:
    volumes:
      - ../../monitoring-mixins/beyla-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/beyla-mixin
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/beyla-mixin/application.json

  mimirtool:
    volumes:
      - ../../monitoring-mixins/beyla-mixin/deploy/beyla-mixin-rules.yaml:/rules/beyla-mixin-rules.yaml
      - ../../monitoring-mixins/beyla-mixin/deploy/beyla-mixin-alerts.yaml:/rules/beyla-mixin-alerts.yaml
