# ============================================================================ #
#                  Monitoring Mixins
# ============================================================================ #
# Provisioning Grafana dashboards Prometheus rules and alerts

# ----------------------------------------------------
# apiVersion and kind of Kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# default enabled
resources:
- go-runtime-mixin/deploy
- kubernetes-mixin/deploy
- mimir-mixin/deploy
# - pyroscope-mixin/deploy
# - tempo-mixin/deploy
# - loki-mixin/deploy
