# ============================================================================ #
#                  Monolithic Mode - Profiles
# ============================================================================ #

# Note: 
# include is available in Docker Compose version 2.20 and later, and Docker Desktop version 4.22 and later.
# docs: https://docs.docker.com/compose/multiple-compose-files/include/#include-and-overrides
include:
  - path: ../../common/compose-include/minio.yaml
  - path: ../../common/compose-include/memcached.yaml
  - path: ../../common/compose-include/pyroscope.yaml
  - path: ../../common/compose-include/mimir.yaml
  - path: ../../common/compose-include/grafana.yaml
  - path: ../../common/compose-include/alloy.yaml

configs:
  alloy_config_file:
    file: ../../common/config/alloy/profiles.alloy
  mimir_config_file:
    file: ../../common/config/mimir/monolithic-mode-metrics.yaml
  pyroscope_config_file:
    file: ../../common/config/pyroscope/monolithic-mode-profiles.yaml

services:
  gateway:
    labels:
      metrics.grafana.com/scrape: false
    depends_on: { pyroscope: { condition: service_healthy } }
    image: ${NGINX_IMAGE:-docker.io/nginxinc/nginx-unprivileged:1.25-alpine}
    volumes:
      - ../../common/config/nginx/10-default-lgtmp.envsh:/docker-entrypoint.d/10-default-lgtmp.envsh
      - ../../common/config/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ../../common/config/pyroscope/gateway_pyroscope.conf:/etc/nginx/templates/gateway_pyroscope.conf.template
      - ../../common/config/mimir/gateway_mimir.conf:/etc/nginx/templates/gateway_mimir.conf.template
    healthcheck:
      test: [ "CMD", "/usr/bin/wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4040/" ]
      interval: 3s
      timeout: 1s
      retries: 20
