# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

resources:
- prometheus-alerts.yaml
- prometheus-rules.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
  annotations:
    grafana_dashboard_folder: "/dashboards/pyroscope-mixin"

configMapGenerator:
- name: pyroscope-reads.json
  files:
  - dashboards_out/pyroscope-reads.json
- name: pyroscope-writes.json
  files:
  - dashboards_out/pyroscope-writes.json
