certManager:
  podAnnotations:
    logs.grafana.com/scrape: "true"

service:
  # Requires prometheus-operator to be installed
  serviceMonitor:
    create: true
    interval: 15s

dashboards:
  certManagerDashboard:
    create: false
