apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sts-certmanager-cert
  namespace: minio-system
spec:
  dnsNames:
    - sts
    - sts.minio-system
    - sts.minio-system.svc
    - sts.minio-system.svc.cluster.local
  secretName: sts-tls
  issuerRef:
    name: minio-system-issuer