apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: grafana-pdc-agent
    app.kubernetes.io/version: 0.0.31
  name: grafana-pdc-agent
  namespace: monitoring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-pdc-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-pdc-agent
    spec:
      containers:
      - args:
        - -cluster
        - $(CLUSTER)
        - -token
        - $(TOKEN)
        - -gcloud-hosted-grafana-id
        - $(HOSTED_GRAFANA_ID)
        envFrom:
        - secretRef:
            name: grafana-pdc-agent-env
            optional: true
        image: docker.io/grafana/pdc-agent:0.0.31
        imagePullPolicy: Always
        name: grafana-pdc-agent
        resources:
          limits:
            cpu: 999m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
          runAsNonRoot: true
      securityContext:
        fsGroup: 30000
        runAsGroup: 30000
        runAsUser: 30000
