name: "Setup identity"
description: "Setup git config with name and email and log in with GH CLI"
inputs:
  token:
    description: "Token to use with GH CLI"
    required: true
  name:
    description: "Git config name"
    required: false
    default: "🤖QC Owl App[bot]"
  email:
    description: "Git config email"
    required: false
    default: "165384878+qc-owl-app[bot]@users.noreply.github.com"
outputs: {}
runs:
  using: "composite"
  steps:
    # add safe.directory is repeated here because it doesn't propagate over the checkout action
    - name: Setup git config
      shell: bash
      run: |
        git config --global --add safe.directory '/__w/codelab-monitoring/codelab-monitoring'
        git config user.name "${INPUTS_NAME}"
        git config user.email "${INPUTS_EMAIL}"
      env:
        INPUTS_NAME: ${{ inputs.name }}
        INPUTS_EMAIL: ${{ inputs.email }}
    - name: Log in with GH CLI
      shell: bash
      run: |
        echo "${INPUTS_TOKEN}" | gh auth login --with-token

      env:
        INPUTS_TOKEN: ${{ inputs.token }}
