apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-system
helmCharts:
- name: grafana
  repo: https://grafana.github.io/helm-charts
  version: 8.8.6
  releaseName: grafana
  namespace: monitoring-system
  includeCRDs: false
  skipTests: true
  valuesFile: values-k3d-k3s.yaml
# images:
# - name: docker.io/grafana/grafana
#   newTag: 11.1.5
# - name: quay.io/kiwigrid/k8s-sidecar
#   newTag: 1.27.4
resources:
- namespace.yaml
configMapGenerator:
- name: grafana
  files:
  - configs/grafana.ini
- name: grafana-datasources
  options:
    immutable: true
    labels:
      grafana_datasource: "1"
  files:
  - configs/datasources.yaml
- name: minio-dashboard.json
  options:
    labels:
      grafana_dashboard: "1"
    annotations:
      grafana_dashboard_folder: "/dashboards"
  files:
  - configs/minio-dashboard.json
- name: home-kubernetes-monitoring.json
  options:
    labels:
      grafana_dashboard: "1"
    annotations:
      grafana_dashboard_folder: "/dashboards"
  files:
  - configs/home-kubernetes-monitoring.json
secretGenerator:
- name: grafana-secret
  literals:
  - admin-user=admin
  - admin-password=admin
- name: grafana-env
  options:
    disableNameSuffixHash: true
  literals:
  - NAMESPACE=monitoring-system
  - GF_LOG_LEVEL=info
  - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor tracesEmbeddedFlameGraph traceqlSearch correlations metricsSummary traceToMetrics traceToProfiles
