# Do not use this configuration in production.
# It is for demonstration purposes only.
multitenancy_enabled: true

# -usage-stats.enabled=false
usage_stats:
  enabled: false

server:
  http_listen_port: 8080
  grpc_listen_port: 9095
  log_level: warn

common:
  storage:
    backend: s3
    s3:
      endpoint:          ${MIMIR_S3_ENDPOINT:minio.minio-system.svc:443}
      access_key_id:     ${MIMIR_S3_ACCESS_KEY_ID:lgtmp}
      secret_access_key: ${MIMIR_S3_SECRET_ACCESS_KEY:supersecret}
      insecure:          ${MIMIR_S3_INSECURE:false}
      http:
        insecure_skip_verify: true

alertmanager:
  data_dir: /data/alertmanager
  enable_api: true
  external_url: /alertmanager
  fallback_config_file: /etc/mimir/alertmanager_fallback_config.yaml
alertmanager_storage:
  s3:
    bucket_name: mimir-alertmanager

memberlist:
  join_members: [ mimir-memberlist:7946 ]


ingester:
  ring:
    replication_factor: 1

store_gateway:
  sharding_ring:
    replication_factor: 1

blocks_storage:
  s3:
    bucket_name: mimir-blocks
  tsdb:
    dir: /data/ingester
    ship_interval: 1m
    block_ranges_period: [ 2h ]
    retention_period: 3h
  bucket_store:
    index_cache:
      backend: memcached
      memcached:
        addresses: dns+memcached.memcached-system.svc:11211

    chunks_cache:
      backend: memcached
      memcached:
        addresses: dns+memcached.memcached-system.svc:11211

    metadata_cache:
      backend: memcached
      memcached:
        addresses: dns+memcached.memcached-system.svc:11211

ruler:
  rule_path: /data/rules
  enable_api: true
  # Each ruler is configured to route alerts to the Alertmanager running within the same component.
  alertmanager_url: http://localhost:8080/alertmanager
ruler_storage:
  s3:
    bucket_name: mimir-ruler
  cache:
    backend: memcached
    memcached:
      addresses: dns+memcached.memcached-system.svc:11211

query_scheduler:
  service_discovery_mode: "ring"

compactor:
  compaction_interval: 30s
  data_dir: /data/mimir-compactor
  cleanup_interval:    1m
  tenant_cleanup_delay: 1m

limits:
  native_histograms_ingestion_enabled: true

overrides_exporter:
  ring:
    enabled: true
    wait_stability_min_duration: 30s

runtime_config:
  file: /etc/mimir/runtime.yaml
