---
name: "Updatecli: Check for dependency updates"

on:
    workflow_dispatch:
    schedule:
      # * is a special character in YAML so you have to quote this string
      # Run once a day
      - cron: '0 7 * * *'

env:
    UPDATECLI_CONFIG_DIR: "${{ github.workspace }}/.github/updatecli.d"

jobs:
    updatecli:
        name: Update dependency helm charts
        runs-on: "ubuntu-latest"
        steps:
            - 
              name: Create Github App[bot] Token
              uses: actions/create-github-app-token@v1
              id: app-token
              with:
                app-id: ${{ vars.APP_ID }}
                private-key: ${{ secrets.PRIVATE_KEY }}
            - 
              name: Checkout
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
            - 
              name: Setup updatecli
              uses: updatecli/updatecli-action@v2
            - 
              name: Run Updatecli
              id: updatecli-apply
              run: |
                updatecli apply --config ${UPDATECLI_CONFIG_DIR}/deps-charts.yaml > changelog.out 2>&1
                if ! git diff --exit-code > /dev/null; then
                  echo "changed=true" >> "${GITHUB_OUTPUT}"
                  echo "body=$(cat changelog.out | awk 'NR >= 22')" >> "${GITHUB_OUTPUT}"
                fi
            - 
              name: Create pull request
              if: steps.updatecli-apply.outputs.changed == 'true'
              uses: peter-evans/create-pull-request@c55203cfde3e5c11a452d352b4393e68b85b4533 #v6.0.3
              with:
                token: ${{ steps.app-token.outputs.token }}
                title: "[updatecli] Bump dependency helm charts version to latest"
                commit-message: Updates dependency helm charts
                committer: 🤖QC Owl App[bot] <165384878+qc-owl-app[bot]@users.noreply.github.com>
                signoff: true
                body: |
                  🤖 Updates Dependency Helm Charts

                  <details>
                  <summary> FULL CHANGELOG </summary>
                  <blockquote>

                  ${{ steps.updatecli-apply.outputs.body }}

                  </blockquote>
                  </details>
                  <br />

                  > Auto-generated by [.github/workflows/updatecli.yml][0]

                  [0]: https://github.com/qclaogui/codelab-monitoring/blob/main/.github/workflows/updatecli.yml
                labels: dependencies
                branch: update-helm-charts
                delete-branch: true
